### ISSUE TITLE
Ne pas utiliser de bouton dans les liens

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/anssi-demain-specialiste-cyber#1]
De nombreux liens sont codés de la manière suivante : `<a href="/la-campagne"><button class="action">Découvre la campagne</button></a>`. 
Il ne faut pas mettre de balise `button` dans les liens. (ce qui n'empêche pas de donner au lien un style de bouton ;)

**Comment by ThibaudMZN** [comment]
Corrigé ! Merci :+1:
