### ISSUE TITLE
Revoir la hierarchie des titres

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/anssi-demain-specialiste-cyber#4]
Sur la page métier, revoir la hierarchie des titres et le balisage général
![Capture d’écran 2023-11-02 à 15 11 54](https://github.com/betagouv/anssi-demain-specialiste-cyber/assets/33344370/e22ece1e-14af-4443-8a81-3664f198d353)

**Comment by ThibaudMZN** [comment]
Corrigé, merci !
