### ISSUE TITLE
Contraste insuffisant

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/anssi-demain-specialiste-cyber#5]
sur les pages d'acueil et métiers, 
le contraste entre la couleur utilisée pour le prénom et le fond n'est pas suffisant
<img width="986" alt="Capture d’écran 2023-11-02 à 15 51 22" src="https://github.com/betagouv/anssi-demain-specialiste-cyber/assets/33344370/02ace174-1822-40e1-a454-3bd8f28d286f">

idem pour le contraste du lien source blanc sur fond rouge
<img width="888" alt="Capture d’écran 2023-11-02 à 15 54 51" src="https://github.com/betagouv/anssi-demain-specialiste-cyber/assets/33344370/35493e89-638b-4680-bd42-db16ef7ae8ab">

**Comment by ThibaudMZN** [comment]
Corrigé !
