### ISSUE TITLE
Structure du document

### ISSUE THREAD

**Issue by benoitdequick** [betagouv/anssi-demain-specialiste-cyber#7]
Les pages ne sont pas structurées avec les balises et roles nécessaires
header, main, nav... 
https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#9.2

**Comment by ThibaudMZN** [comment]
Cela est normalement résolu avec [ce commit](https://github.com/betagouv/anssi-demain-specialiste-cyber/commit/3d7c7eb28f2917889591d2cb6ddd2692a4a4ceed).

La structure est la suivante:
```pug
main
    header
        nav
    ...content
    footer
``` 

Est-ce correct ?

**Comment by ThibaudMZN** [comment]
C'est fait, avec les balises et les rôles
